# -*- coding: utf-8 -*-
"""RAG Data Engineering Pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ahEEdVJJobPes90YgYWMeZDPbfLetBXq

DOCUMENT SOURCES
                       │
             ┌─────────┴─────────┐
             │                   │
           PDFs               TXT/MD
             │                   │
             └─────────┬─────────┘
                       ▼
                DOCUMENT INGESTION
                       │
                       ▼
                DATA VALIDATION
                       │
                       ▼
                 TEXT CLEANING
                       │
                       ▼
                DOCUMENT HASHING
                       │
              ┌────────┴────────┐
              │                 │
         New/Changed        Unchanged
              │                 │
              ▼                 X
           Chunking
              │
              ▼
          Embeddings
              │
              ▼
         FAISS VECTOR DB
              │
              ▼
           Retrieval
              │
              ▼
        RAG Application
"""

# Install dependencies
!pip -q install pypdf sentence-transformers faiss-cpu pandas numpy tqdm

# Required libraries
import os
import re
import json
import hashlib
import pickle
import shutil
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd

from tqdm.auto import tqdm

from pypdf import PdfReader

from sentence_transformers import SentenceTransformer

import faiss

# Project Structure

BASE_DIR = Path("/content/rag_data_engineering")

RAW_DIR = BASE_DIR / "raw"
PROCESSED_DIR = BASE_DIR / "processed"
VECTOR_DIR = BASE_DIR / "vector_store"
METADATA_DIR = BASE_DIR / "metadata"
LOG_DIR = BASE_DIR / "logs"

for directory in [
    RAW_DIR,
    PROCESSED_DIR,
    VECTOR_DIR,
    METADATA_DIR,
    LOG_DIR
]:
    directory.mkdir(parents=True, exist_ok=True)

print("Project directories created.")

# Upload Documents

from google.colab import files

uploaded = files.upload()

for filename, content in uploaded.items():

    output_path = RAW_DIR / filename

    with open(output_path, "wb") as f:
        f.write(content)

    print(f"Uploaded: {filename}")

# Document Ingestion
def generate_document_id(file_path):

    return hashlib.md5(
        str(file_path.name).encode()
    ).hexdigest()

# PDF Extraction
def extract_pdf(file_path):

    reader = PdfReader(str(file_path))

    pages = []

    for page_number, page in enumerate(reader.pages):

        try:
            text = page.extract_text() or ""
        except Exception:
            text = ""

        pages.append({
            "page_number": page_number + 1,
            "text": text
        })

    return pages

# Markdown Extraction
def extract_text_file(file_path):

    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
        text = f.read()

    return [{
        "page_number": None,
        "text": text
    }]

# Unified Ingestion Function
def ingest_document(file_path):

    extension = file_path.suffix.lower()

    document_id = generate_document_id(file_path)

    if extension == ".pdf":

        pages = extract_pdf(file_path)

    elif extension in [".txt", ".md"]:

        pages = extract_text_file(file_path)

    else:

        raise ValueError(
            f"Unsupported file type: {extension}"
        )

    return {
        "document_id": document_id,
        "file_name": file_path.name,
        "file_type": extension,
        "file_path": str(file_path),
        "ingested_at": datetime.utcnow().isoformat(),
        "pages": pages
    }

# Data quality Validation
def validate_document(document):

    errors = []

    if not document["document_id"]:
        errors.append("Missing document ID")

    if not document["file_name"]:
        errors.append("Missing filename")

    if not document["pages"]:
        errors.append("Document contains no pages")

    total_characters = sum(
        len(page["text"])
        for page in document["pages"]
    )

    if total_characters == 0:
        errors.append("Document contains no extractable text")

    return {
        "valid": len(errors) == 0,
        "errors": errors,
        "character_count": total_characters
    }

# Text Cleaning
def clean_text(text):

    if not text:
        return ""

    # Remove excessive whitespace
    text = re.sub(r"\s+", " ", text)

    # Remove repeated newlines
    text = re.sub(r"\n+", "\n", text)

    # Remove leading/trailing spaces
    text = text.strip()

    return text

def clean_document(document):

    for page in document["pages"]:

        page["text"] = clean_text(
            page["text"]
        )

    return document

# Document Checksum using SHA 256
def calculate_file_hash(file_path):

    sha256 = hashlib.sha256()

    with open(file_path, "rb") as f:

        while chunk := f.read(8192):
            sha256.update(chunk)

    return sha256.hexdigest()

# Metadata Catalog
CATALOG_FILE = METADATA_DIR / "document_catalog.json"

def load_catalog():

    if CATALOG_FILE.exists():

        with open(CATALOG_FILE, "r") as f:
            return json.load(f)

    return {}

def save_catalog(catalog):

    with open(CATALOG_FILE, "w") as f:

        json.dump(
            catalog,
            f,
            indent=4
        )

# Detect new and modified documents
def determine_document_status(file_path, catalog):

    file_hash = calculate_file_hash(file_path)

    filename = file_path.name

    if filename not in catalog:

        return "NEW", file_hash

    previous_hash = catalog[filename]["file_hash"]

    if previous_hash != file_hash:

        return "MODIFIED", file_hash

    return "UNCHANGED", file_hash

# Document Chunking
def chunk_text(
    text,
    chunk_size=800,
    overlap=150
):

    words = text.split()

    chunks = []

    start = 0

    while start < len(words):

        end = start + chunk_size

        chunk = " ".join(
            words[start:end]
        )

        if chunk.strip():

            chunks.append(chunk)

        start += chunk_size - overlap

    return chunks

# Create structured chunks
def create_chunks(document):

    chunks = []

    chunk_counter = 0

    for page in document["pages"]:

        text = page["text"]

        page_chunks = chunk_text(text)

        for chunk in page_chunks:

            chunk_id = (
                f"{document['document_id']}_"
                f"{chunk_counter}"
            )

            chunks.append({

                "chunk_id": chunk_id,

                "document_id":
                    document["document_id"],

                "file_name":
                    document["file_name"],

                "page_number":
                    page["page_number"],

                "chunk_index":
                    chunk_counter,

                "text":
                    chunk,

                "created_at":
                    datetime.utcnow().isoformat()

            })

            chunk_counter += 1

    return chunks

# Load Embedding
embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

embedding_dimension = embedding_model.get_sentence_embedding_dimension()
print("Embedding dimension:", embedding_dimension)

# Generate Embeddings
def generate_embeddings(chunks):

    texts = [
        chunk["text"]
        for chunk in chunks
    ]

    embeddings = embedding_model.encode(
        texts,
        batch_size=32,
        show_progress_bar=True,
        normalize_embeddings=True
    )

    return np.array(
        embeddings,
        dtype="float32"
    )

# FAISS Index
def create_faiss_index(embeddings):

    dimension = embeddings.shape[1]

    index = faiss.IndexFlatIP(
        dimension
    )

    index.add(embeddings)

    return index

# Vector Database
INDEX_FILE = VECTOR_DIR / "faiss.index"

METADATA_FILE = VECTOR_DIR / "chunks.pkl"

def save_vector_store(index, chunks):

    faiss.write_index(
        index,
        str(INDEX_FILE)
    )

    with open(METADATA_FILE, "wb") as f:

        pickle.dump(
            chunks,
            f
        )

    print("Vector store saved.")

def load_vector_store():

    index = faiss.read_index(
        str(INDEX_FILE)
    )

    with open(METADATA_FILE, "rb") as f:

        chunks = pickle.load(f)

    return index, chunks

# Complete Pipeline
def run_pipeline():

    catalog = load_catalog()

    all_new_chunks = []

    statistics = {

        "total_files": 0,
        "new_files": 0,
        "modified_files": 0,
        "unchanged_files": 0,
        "failed_files": 0,
        "total_chunks": 0

    }

    for file_path in RAW_DIR.iterdir():

        if file_path.suffix.lower() not in [
            ".pdf",
            ".txt",
            ".md"
        ]:
            continue

        statistics["total_files"] += 1

        status, file_hash = determine_document_status(
            file_path,
            catalog
        )

        print(
            f"{file_path.name}: {status}"
        )

        if status == "UNCHANGED":

            statistics["unchanged_files"] += 1
            continue

        try:

            document = ingest_document(
                file_path
            )

            validation = validate_document(
                document
            )

            if not validation["valid"]:

                print(
                    "Validation failed:",
                    validation["errors"]
                )

                statistics["failed_files"] += 1
                continue

            document = clean_document(
                document
            )

            chunks = create_chunks(
                document
            )

            all_new_chunks.extend(
                chunks
            )

            catalog[file_path.name] = {

                "document_id":
                    document["document_id"],

                "file_hash":
                    file_hash,

                "file_type":
                    document["file_type"],

                "chunk_count":
                    len(chunks),

                "last_processed":
                    datetime.utcnow().isoformat()

            }

            if status == "NEW":
                statistics["new_files"] += 1

            elif status == "MODIFIED":
                statistics["modified_files"] += 1

            statistics["total_chunks"] += len(chunks)

        except Exception as e:

            print(
                f"ERROR processing {file_path.name}: {e}"
            )

            statistics["failed_files"] += 1

    save_catalog(catalog)

    print("\nPIPELINE SUMMARY")
    print("=" * 40)

    for key, value in statistics.items():

        print(
            f"{key}: {value}"
        )

    return all_new_chunks

chunks = run_pipeline()

# Generate Embeddings
embeddings = generate_embeddings(
    chunks
)

print(
    "Embedding shape:",
    embeddings.shape
)

# Build FAISS
index = create_faiss_index(
    embeddings
)

print(
    "Vectors stored:",
    index.ntotal
)

# Save RAG datalayer
save_vector_store(
    index,
    chunks
)

# Build Retrieval Engine
def retrieve_documents(
    query,
    top_k=5
):

    index, chunks = load_vector_store()

    query_embedding = embedding_model.encode(
        [query],
        normalize_embeddings=True
    )

    query_embedding = np.array(
        query_embedding,
        dtype="float32"
    )

    scores, indices = index.search(
        query_embedding,
        top_k
    )

    results = []

    for score, idx in zip(
        scores[0],
        indices[0]
    ):

        if idx == -1:
            continue

        chunk = chunks[idx].copy()

        chunk["similarity_score"] = float(
            score
        )

        results.append(chunk)

    return results

# Test Retrieval
query = """
What is the difference between batch processing
and stream processing?
"""

results = retrieve_documents(
    query,
    top_k=5
)

for result in results:

    print("=" * 80)

    print(
        "File:",
        result["file_name"]
    )

    print(
        "Page:",
        result["page_number"]
    )

    print(
        "Score:",
        round(
            result["similarity_score"],
            4
        )
    )

    print(
        result["text"][:1000]
    )

# Add an LLM
!pip -q install openai
from openai import OpenAI

# API Key Setup
from getpass import getpass

OPENAI_API_KEY = getpass(
    "Enter OpenAI API Key: "
)

client = OpenAI(
    api_key=OPENAI_API_KEY
)

# Create Context
def build_context(results):

    context_parts = []

    for result in results:

        context_parts.append(

            f"""
SOURCE: {result['file_name']}
PAGE: {result['page_number']}

{result['text']}
"""
        )

    return "\n\n".join(
        context_parts
    )

# Generate RAG Response
def generate_rag_answer(query):

    results = retrieve_documents(
        query,
        top_k=5
    )

    context = build_context(
        results
    )

    prompt = f"""
You are a knowledgeable assistant.

Answer the question using ONLY
the provided context.

If the answer cannot be found
in the context, say:

"I could not find the answer
in the provided documents."

Context:

{context}

Question:

{query}
"""

    response = client.responses.create(

        model="gpt-4.1-mini",

        input=prompt
    )

    return response.output_text, results

# Q&A
answer, sources = generate_rag_answer(
    """
    What are the main advantages
    of Apache Spark?
    """
)

print(answer)

print("\nSOURCES")
print("=" * 50)

for source in sources:

    print(
        source["file_name"],
        "| Page:",
        source["page_number"],
        "| Score:",
        round(
            source["similarity_score"],
            3
        )
    )

# Pipeline Monitoring
def generate_pipeline_report(
    chunks,
    statistics=None
):

    report = {

        "pipeline_run_time":
            datetime.utcnow().isoformat(),

        "documents_processed":
            len(
                set(
                    chunk["document_id"]
                    for chunk in chunks
                )
            ),

        "chunks_created":
            len(chunks),

        "embedding_dimension":
            embedding_dimension,

        "vector_count":
            len(chunks),

        "status":
            "SUCCESS"

    }

    report_file = (
        LOG_DIR /
        "pipeline_report.json"
    )

    with open(
        report_file,
        "w"
    ) as f:

        json.dump(
            report,
            f,
            indent=4
        )

    return report

report = generate_pipeline_report(
    chunks
)

print(
    json.dumps(
        report,
        indent=4
    )
)

# Data Quality Metrics
quality_data = []

for chunk in chunks:

    quality_data.append({

        "chunk_id":
            chunk["chunk_id"],

        "document_id":
            chunk["document_id"],

        "file_name":
            chunk["file_name"],

        "page":
            chunk["page_number"],

        "character_count":
            len(chunk["text"]),

        "word_count":
            len(
                chunk["text"].split()
            ),

        "empty":
            len(chunk["text"].strip()) == 0

    })

quality_df = pd.DataFrame(
    quality_data
)

quality_df.head()

print(
    "Total chunks:",
    len(quality_df)
)

print(
    "Empty chunks:",
    quality_df["empty"].sum()
)

print(
    "Average words/chunk:",
    round(
        quality_df["word_count"].mean(),
        2
    )
)